### ISSUE TITLE
Build error with meson in v3 but not in v2

### ISSUE THREAD

**Issue by Biswa96** [libsigcplusplus/libsigcplusplus#69]
* Platform: Microsoft Windows 10
* Build environment: MSYS2/mingw-w64 GCC 10.2.0, meson 0.56.2, ninja 1.10.2
* Command used:

```sh
  meson \
    --buildtype plain \
    --wrap-mode=nofallback \
    -Dauto_features=enabled \
    -Dbuild-documentation=true \
    --default-library both \
    -Dmaintainer-mode=false \
    bin
ninja -C bin
```

* libsigc++ version 2.10.6 can be compiled with meson/ninja but v3.0.6 can not. But CMake works in v3 or in master branch.
* Error:

```c
../sigc++/functors/slot.h:76:8: error: 'unique_ptr' in namespace 'std' does not name a template type
   76 |   std::unique_ptr<adaptor_type> functor_;
      |        ^~~~~~~~~~
../sigc++/functors/slot.h:29:1: note: 'std::unique_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
   28 | #include <memory>
  +++ |+#include <memory>
   29 |
```

If you need further information I can provide.

**Comment by kjellahl** [comment]
sigc++/functors/slot.h in v3.0.6 does include \<memory\>. What's the problem?
I don't understand why the code does not compile.

**Comment by kjellahl** [comment]
I have built sigc++ 3.0.6 with meson/ninja and with CMake on Ubuntu 20.10,
using gcc 10.2.0. Both builds succeed.

When does the error happen? When building the sigc++ library? An example program?
A test program?

It's strange that you can build with CMake, but not with meson/ninja. I suppose
the same compiler is used in both cases. And what about
```
   28 | #include <memory>
  +++ |+#include <memory>
   29 |
```
Obviously \<memory\> is included. Must it be included twice?

**Comment by Biswa96** [comment]
OK, I'll check.

**Comment by kjellahl** [comment]
Don't you find it strange that the compiler says you shall include a file which
*is* included? Could something be wrong with your `memory` file? Or have you
defined a preprocessor macro such as `_GLIBCXX_MEMORY` in your program?
`_GLIBCXX_MEMORY` is the include guard I found in my installation of the C++
standard library. If it's defined when `memory` is included, the inclusion has
no effect.

**Comment by MeerMusik** [comment]
Same error. Same configuration except meson which is Version 0.57.2

Version which can be successfully compiled from Tarball:
* 2.99.13
* 3.0.0
* 3.0.1
* 3.0.2
* 3.0.3
* 3.0.4

Building from Git Master Branch works: YES

Broken Version from Tarball:
* 3.0.6

**Comment by kjellahl** [comment]
I can build libsigc++ 3.0.6 on Ubuntu with no error messages.

The only difference in source code (.h, .cc) between 3.0.4 and 3.0.6 is that
comments have been modified in sigc++/sigc++.h.

The only difference in source code (.h, .cc) between 3.0.6 and the present git
master branch is that some files have been reformatted with clang-format.

When does the compilation fail? When compiling sigc++/signal_base.cc?
When building a test program? Does only one compilation fail? You can test with
`ninja -k 5` or something similar.

**Comment by MeerMusik** [comment]
Building Libsigc++ itself fails very early complainig about <memory>.

`[21/132] "c++" "-Isigc++/libsigc-3.0-0.dll.p" "-Isigc++" "-I../sigc++" "-I." "-I.." "-fdiagnostics-color=always" "-pipe" "-D_FILE_OFFSET_BITS=64" "-std=c++17" "-g" "-Wall" -MD -MQ sigc++/libsigc-3.0-0.dll.p/signal_base.cc.obj -MF "sigc++/libsigc-3.0-0.dll.p/signal_base.cc.obj.d" -o sigc++/libsigc-3.0-0.dll.p/signal_base.cc.obj "-c" ../sigc++/signal_base.cc
FAILED: sigc++/libsigc-3.0-0.dll.p/signal_base.cc.obj 
"c++" "-Isigc++/libsigc-3.0-0.dll.p" "-Isigc++" "-I../sigc++" "-I." "-I.." "-fdiagnostics-color=always" "-pipe" "-D_FILE_OFFSET_BITS=64" "-std=c++17" "-g" "-Wall" -MD -MQ sigc++/libsigc-3.0-0.dll.p/signal_base.cc.obj -MF "sigc++/libsigc-3.0-0.dll.p/signal_base.cc.obj.d" -o sigc++/libsigc-3.0-0.dll.p/signal_base.cc.obj "-c" ../sigc++/signal_base.cc
In file included from ../sigc++/signal.h:28,
                 from C:/Dev/msys64/mingw64/x86_64-w64-mingw32/include/pthread.h:68,
                 from C:/Dev/msys64/mingw64/include/c++/10.2.0/x86_64-w64-mingw32/bits/gthr-default.h:35,
                 from C:/Dev/msys64/mingw64/include/c++/10.2.0/x86_64-w64-mingw32/bits/gthr.h:148,
                 from C:/Dev/msys64/mingw64/include/c++/10.2.0/ext/atomicity.h:35,
                 from C:/Dev/msys64/mingw64/include/c++/10.2.0/memory:75,
                 from ../sigc++/signal_base.h:24,
                 from ../sigc++/signal_base.cc:18:
../sigc++/functors/slot.h:76:8: error: 'unique_ptr' in namespace 'std' does not name a template type
   76 |   std::unique_ptr<adaptor_type> functor_;
      |        ^~~~~~~~~~
../sigc++/functors/slot.h:29:1: note: 'std::unique_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
   28 | #include <memory>
  +++ |+#include <memory>
   29 | 
../sigc++/functors/slot.h: In constructor 'sigc::internal::typed_slot_rep<T_functor>::typed_slot_rep(const T_functor&)':
../sigc++/functors/slot.h:83:24: error: class 'sigc::internal::typed_slot_rep<T_functor>' does not have any field named 'functor_'
   83 |   : slot_rep(nullptr), functor_(std::make_unique<adaptor_type>(functor))
      |                        ^~~~~~~~
../sigc++/functors/slot.h:83:38: error: 'make_unique' is not a member of 'std'
   83 |   : slot_rep(nullptr), functor_(std::make_unique<adaptor_type>(functor))
      |                                      ^~~~~~~~~~~
../sigc++/functors/slot.h:83:38: note: 'std::make_unique' is defined in header '<memory>'; did you forget to '#include <memory>'?
../sigc++/functors/slot.h:83:62: error: expected primary-expression before '>' token
   83 |   : slot_rep(nullptr), functor_(std::make_unique<adaptor_type>(functor))
      |                                                              ^
../sigc++/functors/slot.h:85:53: error: 'functor_' was not declared in this scope; did you mean 'functor'?
   85 |     sigc::visit_each_trackable(slot_do_bind(this), *functor_);
      |                                                     ^~~~~~~~
      |                                                     functor
../sigc++/functors/slot.h: In copy constructor 'sigc::internal::typed_slot_rep<T_functor>::typed_slot_rep(const sigc::internal::typed_slot_rep<T_functor>&)':
../sigc++/functors/slot.h:89:26: error: class 'sigc::internal::typed_slot_rep<T_functor>' does not have any field named 'functor_'
   89 |   : slot_rep(src.call_), functor_(std::make_unique<adaptor_type>(*src.functor_))
      |                          ^~~~~~~~
../sigc++/functors/slot.h:89:40: error: 'make_unique' is not a member of 'std'
   89 |   : slot_rep(src.call_), functor_(std::make_unique<adaptor_type>(*src.functor_))
      |                                        ^~~~~~~~~~~`

And so on. Well it works with latest Git Master, so this is zero Priority for me right now - until it also breaks in Git Master. Just wanted to confirm (Just-In-Case) and tell people to try other Versions if they can.

Maybe the Tarball was packed slightly differently and caused Issues on MSYS2. I dont know. All Archives were unpacked with 7-zip 21.01 Alpha. I also unpacked the 3.0.6 Archive with tar but that gave the same result.

**Comment by kjellahl** [comment]
I'm surprised at finding `In file included from ../sigc++/signal.h:28`.
That file should not be included from anywhere when signal_base.cc is compiled.

I wonder if this is similar to what I reported in https://github.com/mesonbuild/meson/issues/8562.
A system file includes the system file signal.h, but the preprocessor finds sigc++/signal.h.
If that's the problem, it explains why the git master branch works, but at the same time
it's surprising that libsigc++ 3.0.4 does not fail in the same way as 3.0.6.

It would be fine if you could test what happens, if you add `implicit_include_directories: false,`
to the library() function in sigc++/meson.build in 3.0.6. E.g. as in the git master branch:
```
sigcxx_library = library('sigc-' + sigcxx_api_version,
  source_cc_files,
  extra_sigc_objects,
  version: sigcxx_libversion,
  darwin_versions: darwin_versions,
  implicit_include_directories: false,       # new line
  include_directories: extra_include_dirs,
  cpp_args: extra_sigc_cppflags,
  dependencies: sigcxx_build_dep,
  install: true,
)
```

**Comment by MeerMusik** [comment]
I tested the change and now 3.0.6 from Tarball compiles correctly.

FYI: Offtopic Hint: When Building the Docs there are some Warnings about outdated Variables:
`warning: Tag 'TCL_SUBST' at line 35 of file 'reference/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'COLS_IN_ALPHA_INDEX' at line 151 of file 'reference/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: argument 'a4wide' for option PAPER_TYPE is not a valid enum value
Using the default: a4!`

Doxygen Version: 1.9.1

Have a safe and sunny weekend

**Comment by kjellahl** [comment]
Thanks for the test. I'm sure it has solved the problem. It's unfortunate that I
didn't notice much earlier that Meson by default adds include directories that
are highly unwanted when libsigc++ is being compiled.

Two of the three Doxygen warnings have been fixed in the master branch.
The COLS_IN_ALPHA_INDEX warning will be fixed some time. Such warnings from
new versions of Doxygen have low priority.
